#
#   AUTH
#
CAMAP_KEY=${CAMAP_KEY}
JWT_ACCESS_TOKEN_SECRET=${JWT_ACCESS_TOKEN_SECRET}
JWT_ACCESS_TOKEN_EXPIRATION_TIME=900
JWT_REFRESH_TOKEN_SECRET=${JWT_REFRESH_TOKEN_SECRET}
JWT_REFRESH_TOKEN_EXPIRATION_TIME=2629746
DISABLE_BRUTE_FORCE=${DISABLE_BRUTE_FORCE}

#
#   DB
#
DB_CONNECTION=mysql
DB_HOST=${DB_HOST}
DB_USERNAME=${DB_USERNAME}
DB_PASSWORD=${DB_PASSWORD}
DB_DATABASE=${DB_DATABASE}
DB_PORT=${DB_PORT}
DB_SYNCHRONIZE=false
DB_ENTITIES=./dist/**/*.entity.js
DB_LOGGING=false

#
#   MAIL
#
MAILER_TRANSPORT=smtp
SMTP_HOST=${SMTP_HOST}
SMTP_PORT=${SMTP_PORT}
SMTP_SECURE=${SMTP_SECURE}
SMTP_IGNORE_TLS=${SMTP_IGNORE_TLS}
SMTP_TLS_SERVERNAME=${SMTP_TLS_SERVERNAME}
SMTP_AUTH_USER=${SMTP_AUTH_USER}
SMTP_AUTH_PASS=${SMTP_AUTH_PASS}

#
#   MAPBOX
#
MAPBOX_KEY=${MAPBOX_KEY}

#
#   MISC
#
API_HOSTNAME=0.0.0.0
API_PORT=3010
CAMAP_HOST=${CAMAP_HOST}
CAMAP_LOCAL_HOST=${CAMAP_LOCAL_HOST}
CAMAP_BRIDGE_API=${CAMAP_BRIDGE_API}
FRONT_URL=${FRONT_URL}
FRONT_GRAPHQL_URL=/graphql
HX_TRIGGER_CRONS=${HX_TRIGGER_CRONS}

# DESACTIVATION VERIF TLS
# NODE_TLS_REJECT_UNAUTHORIZED=0

# DEBUG
DB_LOGGING=true

#
#   THEME
#
THEME_ID=${THEME_ID}