apiVersion: v1
kind: Service
metadata:
  name: mailpit
  labels:
    app: mailpit
spec:
  selector:
    app: mailpit
  ports:
    - name: smtp
      port: {{ .Values.mailpit.service.smtpPort }}
      targetPort: smtp
    - name: http
      port: {{ .Values.mailpit.service.httpPort }}
      targetPort: http
