{{- if .Values.certificates.enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "camap.fullname" . }}-api
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "camap.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: api
spec:
  secretName: {{ include "camap.fullname" . }}-api-tls
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  dnsNames:
    - {{ .Values.ingress.api.host | quote }}
{{- end }}
