{{- if and .Values.ingress.enabled .Values.ingress.web.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "camap.fullname" . }}-web
  labels:
    {{- include "camap.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingress.className | quote }}
    nginx.ingress.kubernetes.io/proxy-body-size: {{ .Values.ingress.bodySize | quote }}
    nginx.ingress.kubernetes.io/proxy-read-timeout: {{ .Values.ingress.timeouts.read | quote }}
    nginx.ingress.kubernetes.io/proxy-send-timeout: {{ .Values.ingress.timeouts.send | quote }}
    nginx.ingress.kubernetes.io/proxy-connect-timeout: {{ .Values.ingress.timeouts.connect | quote }}
    nginx.ingress.kubernetes.io/ssl-redirect: {{ .Values.ingress.web.tls.enabled | toString | quote }}
    {{- if .Values.ingress.web.tls.clusterIssuer }}
    cert-manager.io/cluster-issuer: {{ .Values.ingress.web.tls.clusterIssuer | quote }}
    {{- end }}
    {{- if and (not .Values.ingress.web.tls.clusterIssuer) .Values.ingress.web.tls.issuer }}
    cert-manager.io/issuer: {{ .Values.ingress.web.tls.issuer | quote }}
    {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className | quote }}
  {{- if .Values.ingress.web.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.ingress.web.host }}
      secretName: {{ include "camap.tlsSecretNameWeb" . }}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.web.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "camap.fullname" . }}-web
                port:
                  number: 80
{{- end }}
