apiVersion: v1
kind: Service
metadata:
  name: {{ include "camap.fullname" . }}-api
  labels:
    {{- include "camap.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: {{ include "camap.name" . }}
    app.kubernetes.io/component: api
  ports:
    - name: http
      port: 3010
      targetPort: 3010
